### PR TITLE
Disallow .mid files with multiple track name events

### PR DESCRIPTION
**Pull request by TheNathannator**
Because these files just needed *yet another* edge-case for us to handle...

### CODE REVIEW

**Comment by sonicfind** [comment]
Gonna add some changes to the YARGMidiTrack function to have it return the trackname string instead of the trackType.

**Comment by sonicfind** [comment]
Because we can do that, lol

**Comment by TheNathannator** [comment]
Your changes to `FindTrackName` defeat the entire purpose of the PR lol, now it once again only takes the first track name in the file.

**Comment by TheNathannator** [comment]
Not too enthused about this PR turning into the opposite of what it was originally supposed to be, but since everyone else seems to be against allowing multiple track names, I guess there's not much I can argue against.

**Pull request merged**
