### PR TITLE
Improve Drum Preparse Handling

### PR DESCRIPTION
**Pull request by sonicfind**
+ Fixes drum scans for CON update files being overridden by the original midi file.

+ Reorder and restructure songini preparse functions

+ Fix ParseSettings not receiving the drumType

### CODE REVIEW

**Comment by jgoyvaerts** [comment]
Shouldn't we write unit tests for this stuff?

**Comment by sonicfind** [comment]
Unit testing an entire complex system that is extremely dependent on slight differences  in user provided data (a lot of which are very minuscule) is a fools errand. The best test you can ever do is with real samples of data, of which you know the desired result.

It's why SongScanning test exists really. You can provide the folder/song to scan and compared the resulting entry or entries to what you expected to receive.

**Comment by jgoyvaerts** [comment]
I guess unit testing was a poor choice of word. I mean an integration test which loads a (custom crafted) midi file and verifies the cymbals are correct.

The complexity of the system should not be an excuse not to write any kind of tests, on the contrary. The more complex the system, the more useful tests can be.

**Comment by sonicfind** [comment]
Integration makes more sense, yea. I guess the issue with how it works is that you can't just have *one* file. You'd really need dozens or hundreds of fully arranged directories to contain all the possible test cases that you'd need to consider. Some with ini files, some with no audio, some with inis that *fail* to parse, some with ini data that contradicts the midi files, midi files with bad data, midi files with no data, .chart files and all those bring, .chart files *in the same folder as .mid files*, CON files with their own quirks.

Trying to set that up takes an enormous amount of time, of which for a lively-updated game, and for a feature of which had a short time limit on pushing out initially to start with, we don't really have. Furthermore, we'd probably need to have a completely separate integration testing repo with all those mock files so as to not force every person to download the whole suite of files that they probably won't ever even touch.

**Comment by TheNathannator** [comment]
Unit/integration testing is something we should definitely set up more often, the main reason we haven't is just because it takes a lot of time and effort which could also be spent elsewhere lol, especially on edge cases.

You're always welcome to PR tests if you get around to them, I'm personally not very experienced with them so I don't think about it often.

**Pull request merged**
